### ISSUE TITLE
support editing shp files?

### ISSUE THREAD

**Issue by bouyeijiang** [NetTopologySuite/NetTopologySuite.IO.ShapeFile#18]
support editing shp files?

**Comment by airbreather** [comment]
The best you can do is read the whole file, make your edits, and then write the whole file back.

The way that the shapefile format is designed, you actually probably wouldn't be able to do much better than that while still conforming to the standard*, since adding or deleting a point on a feature near the beginning of the file will (eventually) require you to shift the subsequent bytes in the file *and* edit the index file accordingly *and* edit the header at the beginning.
*Admittedly, I'm not sure if any nonstandard tricks in support of this are so common that they've become a *de-facto* standard

**Comment by KubaSzostak** [comment]
If you want update feature attributes, then from technical point of view it is possible. DBF records have fixed size, so they can be updated in place. It is not supported by this library, though. If you want update SHP geometry, then it is not possible. Shapefile is a variable-record-length file in which each record describing a shape can have different size. So there is no way to update it in place.
